### ISSUE TITLE
What can be done with this?

### ISSUE THREAD

**Issue by jhouxzirrus** [DavidKou/EmbeddedFirefoxBrowser#1]
This question sounds pretty "general" and I feel silly asking it, but I found it difficult to find any clear information from Googling about Gecko.

Is there a documented interface somewhere that shows what you can do when interfacing with the browser in C#?

Can you interact directly with the DOM?

I'm looking for a way to build HTML5/CSS3 frontend application without having to use javascript or javascript interop.  I want to directly read and write to DOM from C#.

**Comment by lib6d** [comment]
@jhouxzirrus 
- This is official documentation you can rely on: https://developer.mozilla.org/en-US/docs/Mozilla/Gecko
- For manipulation DOM, HtmlAgilityPack is your friend! Very powerful! https://html-agility-pack.net/

**Comment by DavidKou** [comment]
@jhouxzirrus Closed this issue since it is a question.
